### ISSUE TITLE
Implement 'Define' token feature - Hacktoberfest

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/minirule#1]
We need to implement a 'Define' feature in Minirule to allow users to define custom terms or aliases. This will enhance the flexibility and readability of the rules.

### Tasks

1. [ ] Add 'Define' and 'As' keyword tokens
   - Update `keywords` array in `tokenConfig.ts`
   - Add new tokens in `grammar.ts`

2. [ ] Implement 'define' clause in the parser
   - Add a new rule in `RuleParser` class in `grammar.ts`
   - Update relevant existing rules to incorporate 'define' clause

3. [ ] Implement visitor for 'define' clause in the interpreter
   - Add a new visitor method in `interpreter.ts`
   - Update the interpretation logic to handle defined terms

4. [ ] Add new keyword tokens to playground editor config
   - Update `editor-language.ts` in the playground package
   - Ensure new keywords are recognized for syntax highlighting

### Example Syntax
```sql
DEFINE customer_type AS "Premium"
RULE loyal_customer_discount
WHEN customer.type IS customer_type
THEN APPLY 10% DISCOUNT TO total
END
```

### Acceptance Criteria
- 'Define' and 'As' keywords are recognized by the parser
- Rules can use defined terms in conditions and actions
- Playground correctly highlights 'Define' and 'As' keywords
- Interpreter correctly handles and applies defined terms
