### ISSUE TITLE
Add support for 'Or' logical operator - hacktoberfest

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/minirule#3]
We need to add support for the 'Or' logical operator in Minirule to allow for more complex rule conditions.

## Tasks
- [ ] Add 'Or' keyword token
- [ ] Implement 'or' clause in the parser
- [ ] Implement visitor for 'or' clause in the interpreter
- [ ] Add new keyword token to playground editor config

### 1. Add 'Or' keyword token
- Update `tokenConfig.ts` to include 'Or' in the keywords object
- Add 'Or' to the list of tokens in `grammar.ts`

### 2. Implement 'or' clause in the parser
- Modify the `condition` rule in `RuleParser` class in `grammar.ts` to support 'or' conditions
- Update the `CONDITION` method to handle 'or' clauses

### 3. Implement visitor for 'or' clause in the interpreter
- Update the `visitCondition` method in `interpreter.ts` to evaluate 'or' conditions
- Implement logic to return true if any of the conditions in the 'or' clause are true

### 4. Add new keyword token to playground editor config
- Update the Monaco editor configuration in the playground to recognize and highlight the 'Or' keyword

## Example Usage
```sql
rule "Special Offer"
when
  customer.status is "gold"
  or customer.lifetime_value > 10000
then
  apply 15% discount to order.total
end
```

## Acceptance Criteria
-  'Or' keyword is recognized by the parser
-  Rules with 'or' conditions are correctly interpreted
-  'Or' keyword is properly highlighted in the playground
